#pragma once

#include "Command.hpp"
#include "CommandTypes/MonochromeCommand.hpp"
#include "CommandTypes/NegativeCommand.hpp"
#include "CommandTypes/GrayscaleCommand.hpp"
#include "CommandTypes/HelpCommand.hpp"
#include "CommandTypes/SaveAsCommand.hpp"
#include "CommandTypes/SaveCommand.hpp"
#include "CommandTypes/AddCommand.hpp"
#include "CommandTypes/FlipCommand.hpp"
#include "CommandTypes/RotateCommand.hpp"
#include "CommandTypes/RedoCommand.hpp"
#include "CommandTypes/UndoCommand.hpp"
#include "CommandTypes/ExitCommand.hpp"